# Generated by Django 6.0.6 on 2026-06-08 03:06

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import empleados.validators.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID) del área corporativa.', primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre único identificativo del área corporativa, sin numeros ni simbolos, no menor a 2 letras(ej. Tecnología, Recursos Humanos).', max_length=100, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(message='Este campo solo debe contener letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')])),
                ('descripcion', models.TextField(blank=True, help_text='Breve descripción de las funciones y responsabilidades del área (máximo 1000 caracteres).', null=True, validators=[django.core.validators.MaxLengthValidator(1000), django.core.validators.RegexValidator(message='El texto contiene caracteres no permitidos (solo se permiten letras, números y puntuación básica).', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\\s.,;:\\-()¿?¡!"\\\'\\n]+$')])),
            ],
            options={
                'db_table': 'areas',
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='unique_area_nombre_ci')],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID) del cargo.', primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre asignado al cargo u ocupación dentro de la empresa.', max_length=100, validators=[django.core.validators.RegexValidator(message='Este campo solo debe contener letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')])),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de las tareas asignadas al cargo (máximo 500 caracteres).', null=True, validators=[django.core.validators.MaxLengthValidator(500)])),
                ('area', models.ForeignKey(help_text='Área organizativa a la que pertenece estructuralmente este cargo.', on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='empleados.area')),
            ],
            options={
                'db_table': 'cargos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID) del empleado.', primary_key=True, serialize=False)),
                ('numero_documento', models.CharField(help_text='Número de documento de identidad único del empleado.', max_length=50)),
                ('nombre', models.CharField(help_text='Nombre completo del empleado.', max_length=150, validators=[django.core.validators.RegexValidator(message='Este campo solo debe contener letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')])),
                ('correo', models.EmailField(help_text='Dirección de correo electrónico institucional o de contacto del empleado.', max_length=254)),
                ('fecha_ingreso', models.DateField(help_text='Fecha oficial en la que el empleado ingresó a trabajar en la empresa.', validators=[empleados.validators.validators.validar_fecha_ingreso])),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', help_text='Estado operativo del empleado en el sistema (ACTIVO/INACTIVO).', max_length=10)),
                ('cargo', models.ForeignKey(help_text='Cargo oficial asignado que define sus funciones laborales.', on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='empleados.cargo')),
            ],
            options={
                'db_table': 'empleados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCambio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID) de la auditoría de cambio.', primary_key=True, serialize=False)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora exacta en la que se efectuó y registró el cambio de manera automática.')),
                ('tipo_cambio', models.CharField(choices=[('CREACION', 'Creación'), ('ACTUALIZACION', 'Actualización')], help_text='Tipo de operación ejecutada sobre el registro del empleado (CREACION, ACTUALIZACION, ELIMINACION).', max_length=20)),
                ('campo_cambiado', models.CharField(help_text='Nombre del atributo o columna específica que fue modificada.', max_length=100)),
                ('valor_anterior', models.TextField(blank=True, help_text='Valor que tenía el campo antes del cambio (permanece vacío si el tipo es CREACION).', null=True)),
                ('valor_nuevo', models.TextField(blank=True, help_text='Nuevo valor asignado al campo tras la modificación realizada.', null=True)),
                ('empleado', models.ForeignKey(help_text='Empleado que sufrió la modificación en sus datos.', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='empleados.empleado')),
            ],
            options={
                'db_table': 'historial_cambios',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.AddConstraint(
            model_name='cargo',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='unique_cargo_nombre_ci'),
        ),
        migrations.AddConstraint(
            model_name='empleado',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('correo'), name='unique_correo_ci'),
        ),
        migrations.AddConstraint(
            model_name='empleado',
            constraint=models.UniqueConstraint(models.F('numero_documento'), name='unique_documento'),
        ),
    ]
