# Generated by Django 6.0.5 on 2026-06-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='area',
        ),
    ]
